### ISSUE TITLE
Remove all cookie if device is offline

### ISSUE THREAD

**Issue by jurihahn** [GEDYSIntraWare/cordova-plugin-webview-proxy#10]
if I need to logout and can not make request to server, I want just to delete cookie.
document.cookie is always empty. And it is not possible to just remove all cookies?

We need anything like `window.WebviewProxy.clearCookie()`

**Comment by NiklasMerz** [comment]
Thank you for using this plugin and this report. As we currently don't need this feature, I don't think I would implement it myself soon. I would love to review a pull request though.

You could try to implement this feature yourself. The cookies are stored in WKHTTPCookieStore and you could implement a clearFunction which iterates through them and deletes them.

Here is the cookie store: https://github.com/GEDYSIntraWare/cordova-plugin-webview-proxy/blob/2663ad67c7d4bc5d7af8c02e7f06977a0750ceb0/src/ios/WebviewProxy.m#L36-L37

**Comment by jurihahn** [comment]
This is my first code in Objective-C, I hope it's OK?
