### ISSUE TITLE
Requests time out after 60 seconds

### ISSUE THREAD

**Issue by adamdport** [GEDYSIntraWare/cordova-plugin-webview-proxy#2]
**Describe the bug**
Requests time out after 60 seconds

**To Reproduce**
Make a request that takes longer than 60s to resolve

**Expected behavior**
I was able to get past this by setting my own setTimeoutInterval on the request, but this probably needs to be made configurable

**Comment by NiklasMerz** [comment]
The default timeout of NSURLSession is indeed 60 seconds: https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1408259-timeoutintervalforrequest

I will try to find a solution for that.

**Comment by NiklasMerz** [comment]
I have set the timeout to 30 minutes for now. Nobody waits for more than 30 for a single HTTP request I guess.

If we want a configuration for that we can add this later with Cordova preferences.
