### ISSUE TITLE
Add Android support

### ISSUE THREAD

**Issue by contfedorov** [GEDYSIntraWare/cordova-plugin-webview-proxy#24]
**Is your feature request related to a problem? Please describe.**
Sometimes I meet CORS issues on Android devices/simulators as well.

**Describe the solution you'd like**
It would be helpful to have the same proxy functionality on Android platform.

**Describe alternatives you've considered**
[`cordova-plugin-advanced-http`](https://github.com/silkimen/cordova-plugin-advanced-http) can be treated as alternative. CORS restrictions do not apply for it. But it is full-featured HTTP client which functionality in many points exceeds required minimum. Single lightweight plugin for this particular task would be preferable.

**Comment by NiklasMerz** [comment]
We did some experimentation to see if we could implement the feature on Android similar to iOS. Unfortunately the WebView on Android does not have the necessary API for implementing this plugin. We could make GET requests work but POST requests are a problem.

Please check out the code and comments https://github.com/GEDYSIntraWare/cordova-plugin-webview-proxy/pull/17

If Android introduces a more powerful API this could change in the future but I don't think this is very likely.

**Comment by contfedorov** [comment]
@NiklasMerz 
Thanks. Just found a workaround for CORS problem that is built-in to cordova-android. Updated my first post accordingly. Tested for GET requests only.

**Comment by NiklasMerz** [comment]
Be careful. As the name already suggests this makes your app less secure and Google discourages this.
