### ISSUE TITLE
window.CDV_ASSETS_URL is undefined, leading to nothing being proxied

### ISSUE THREAD

**Issue by mattdsteele** [GEDYSIntraWare/cordova-plugin-webview-proxy#5]
**Describe the bug**

See my comment in #3 for more details.

Environment: in a new Cordova application (built with `cordova create`) and these plugins installed:

```
    <plugin name="cordova-plugin-webview-proxy" spec="0.0.3" />
    <engine name="ios" spec="^6.2.0" />
```

I'm launching the application on an iPhone running iOS 14.4 and opening the Safari Developer Tools.

Running `window.WebviewProxy.convertProxyUrl('https://example.com'));` returns `https://example.com`, with no new protocol prefixed. As a result, requests are not proxied through this plugin, and requests to external servers fail for CORS reasons.

Investigating further, I see that `window.CDV_ASSETS_URL` returns `undefined`, which results in this line being returned: https://github.com/GEDYSIntraWare/cordova-plugin-webview-proxy/blob/master/www/WebviewProxy.js#L8

Any idea why this might be happening? I can verify that the platform is on the latest version (running `cordova.platformVersion` === `6.2.0`).

**Comment by NiklasMerz** [comment]
Is your app running on a custom scheme? This is now part of cordova-ios (https://github.com/apache/cordova-ios/pull/781). You need to set a scheme and hostname in config.xml to make your app run on let's say `app://myapp` instead of `file://index.html` and this proxy just works with the custom scheme.

We might need to document this in the documentation for cordova-ios.

**Comment by mattdsteele** [comment]
Yup, that was the issue! I've added a custom scheme in my config.xml

```
        <allow-navigation href="cdv://*" />
        <preference name="scheme" value="cdv" />
        <preference name="hostname" value="foobar" />
```

And I'm able to proxy requests now.

I am still not seeing cookies being sent, but I'll focus that on the original #3 ticket.

Thank you!
