### ISSUE TITLE
[BUG] Memory leak

### ISSUE THREAD

**Issue by ghost** [GEDYSIntraWare/cordova-plugin-webview-proxy#8]
Dear Alls,
After I apply this plugin, the Cookies is store.
However, when i check memory leak via XCode Instruments tool, this tool detected memory leak as below:
`100.00% [[NSHTTPCookieStorage sharedHTTPCookieStorage] setCookies:cookies forURL:httpResponse.URL mainDocumentURL:nil];
`
If you have any suggestion, please let me known.
Thanks

**Comment by NiklasMerz** [comment]
I could not find any issues so far. If anyone is familiar with ObjectiveC, iOS and these tools let me know.
