### ISSUE TITLE
[BUG] lowest supported ios api level?

### ISSUE THREAD

**Issue by meszarosg** [GEDYSIntraWare/cordova-plugin-webview-proxy#9]
Hi all,

Thanks for the awesome plugin!

We have ios cordova core 6.2. 
We use the plugin on ios 13 and ios 14 with more or less success.
We realized that the intercepting of request is not perfect on ios 12.
The body of the request is always nil on my iphone 6 ios 12.5.2. here:
https://github.com/GEDYSIntraWare/cordova-plugin-webview-proxy/blob/master/src/ios/WebviewProxy.m#L27

Can you confirm that this is a bug? or what is the lowest supported ios api level for the plugin?
Do you have any suggestions for poor developers who must support old ios12 for client demand?

I am not an objective c ninja, please let me know if I see the situation wrongly.

Regards,
Gabor

**Comment by NiklasMerz** [comment]
I am not sure exactly sure but I remember issues with iOS 12. This plugin was built for iOS 13 and aims to support the latest iOS version. Unfortunately I can do nothing about older versions.
